

library(bipartite)
a<-read.table("dadax.txt",header=T)
w1<-data.frame(frame2webs(a, varnames= c("Planta", "Bitxo", "Parcela", "Frequencia"), type.out="list", emptylist="F"))

plotweb(w1, method="cca")

plot1 <- a[a$Parcela == 1,]

plot1TVUF <- plot1[plot1$Planta == "TVUF",]

# calcul strength de cada sp de bitxo sobre una planta seleccionada previament
w1<-data.frame(frame2webs(plot34TVUH, varnames= c("Planta", "Bitxo", "Parcela", "Frequencia"), type.out="list", emptylist="F"))
s1 <- strength(w1, type="Barrat")
s1

# calcul de lindex de diversitat de simpson
library(untb)

Simpson<-numeric(40)
Simpson[1]<-simpson(plot1$Frequencia,FALSE)
Simpson[2]<-simpson(plot2$Frequencia,FALSE)
Simpson[3]<-simpson(plot3$Frequencia,FALSE)
Simpson[4]<-simpson(plot4$Frequencia,FALSE)
Simpson[5]<-simpson(plot5$Frequencia,FALSE)
Simpson[6]<-simpson(plot6$Frequencia,FALSE)
Simpson[7]<-simpson(plot7$Frequencia,FALSE)
Simpson[8]<-simpson(plot8$Frequencia,FALSE)
Simpson[9]<-simpson(plot9$Frequencia,FALSE)
Simpson[10]<-simpson(plot10$Frequencia,FALSE)
Simpson[11]<-simpson(plot11$Frequencia,FALSE)
Simpson[12]<-simpson(plot12$Frequencia,FALSE)
Simpson[13]<-simpson(plot13$Frequencia,FALSE)
Simpson[14]<-simpson(plot14$Frequencia,FALSE)
Simpson[15]<-simpson(plot15$Frequencia,FALSE)
Simpson[16]<-simpson(plot16$Frequencia,FALSE)
Simpson[17]<-simpson(plot17$Frequencia,FALSE)
Simpson[18]<-simpson(plot18$Frequencia,FALSE)
Simpson[19]<-simpson(plot19$Frequencia,FALSE)
Simpson[20]<-simpson(plot20$Frequencia,FALSE)
Simpson[21]<-simpson(plot21$Frequencia,FALSE)
Simpson[22]<-simpson(plot22$Frequencia,FALSE)
Simpson[23]<-simpson(plot23$Frequencia,FALSE)
Simpson[24]<-simpson(plot24$Frequencia,FALSE)
Simpson[25]<-simpson(plot25$Frequencia,FALSE)
Simpson[26]<-simpson(plot26$Frequencia,FALSE)
Simpson[27]<-simpson(plot27$Frequencia,FALSE)
Simpson[28]<-simpson(plot28$Frequencia,FALSE)
Simpson[29]<-simpson(plot29$Frequencia,FALSE)
Simpson[30]<-simpson(plot30$Frequencia,FALSE)
Simpson[31]<-simpson(plot31$Frequencia,FALSE)
Simpson[32]<-simpson(plot32$Frequencia,FALSE)
Simpson[33]<-simpson(plot33$Frequencia,FALSE)
Simpson[34]<-simpson(plot34$Frequencia,FALSE)
Simpson[35]<-simpson(plot35$Frequencia,FALSE)
Simpson[36]<-simpson(plot36$Frequencia,FALSE)
Simpson[37]<-simpson(plot37$Frequencia,FALSE)
Simpson[38]<-simpson(plot38$Frequencia,FALSE)
Simpson[39]<-simpson(plot39$Frequencia,FALSE)
Simpson[40]<-simpson(plot40$Frequencia,FALSE)

Simpson[1]<-simpson(plot1TVUF$Frequencia,FALSE)
Simpson[2]<-simpson(plot2TVUF$Frequencia,FALSE)
Simpson[3]<-simpson(plot3TVUF$Frequencia,FALSE)
Simpson[4]<-simpson(plot4TVUF$Frequencia,FALSE)
Simpson[5]<-simpson(plot5TVUF$Frequencia,FALSE)
Simpson[6]<-simpson(plot6TVUF$Frequencia,FALSE)
Simpson[7]<-simpson(plot7TVUF$Frequencia,FALSE)
Simpson[8]<-simpson(plot8TVUF$Frequencia,FALSE)
Simpson[9]<-simpson(plot9TVUF$Frequencia,FALSE)
Simpson[10]<-simpson(plot10TVUF$Frequencia,FALSE)
Simpson[11]<-simpson(plot11TVUF$Frequencia,FALSE)
Simpson[12]<-simpson(plot12TVUF$Frequencia,FALSE)
Simpson[13]<-simpson(plot13TVUF$Frequencia,FALSE)
Simpson[14]<-simpson(plot14TVUF$Frequencia,FALSE)
Simpson[15]<-simpson(plot15TVUF$Frequencia,FALSE)
Simpson[16]<-simpson(plot16TVUF$Frequencia,FALSE)
Simpson[17]<-simpson(plot17TVUF$Frequencia,FALSE)
Simpson[18]<-simpson(plot18TVUF$Frequencia,FALSE)
Simpson[19]<-simpson(plot19TVUF$Frequencia,FALSE)
Simpson[20]<-simpson(plot20TVUF$Frequencia,FALSE)
Simpson[21]<-simpson(plot21TVUF$Frequencia,FALSE)
Simpson[22]<-simpson(plot22TVUF$Frequencia,FALSE)
Simpson[23]<-simpson(plot23TVUF$Frequencia,FALSE)
Simpson[24]<-simpson(plot24TVUF$Frequencia,FALSE)
Simpson[25]<-simpson(plot25TVUF$Frequencia,FALSE)
Simpson[26]<-simpson(plot26TVUF$Frequencia,FALSE)
Simpson[27]<-simpson(plot27TVUF$Frequencia,FALSE)
Simpson[28]<-simpson(plot28TVUF$Frequencia,FALSE)
Simpson[29]<-simpson(plot29TVUF$Frequencia,FALSE)
Simpson[30]<-simpson(plot30TVUF$Frequencia,FALSE)
Simpson[31]<-simpson(plot31TVUF$Frequencia,FALSE)
Simpson[32]<-simpson(plot32TVUF$Frequencia,FALSE)
Simpson[33]<-simpson(plot33TVUF$Frequencia,FALSE)
Simpson[34]<-simpson(plot34TVUF$Frequencia,FALSE)
Simpson[35]<-simpson(plot35TVUF$Frequencia,FALSE)
Simpson[36]<-simpson(plot36TVUF$Frequencia,FALSE)
Simpson[37]<-simpson(plot37TVUF$Frequencia,FALSE)
Simpson[38]<-simpson(plot38TVUF$Frequencia,FALSE)
Simpson[39]<-simpson(plot39TVUF$Frequencia,FALSE)
Simpson[40]<-simpson(plot40TVUF$Frequencia,FALSE)
