

library(bipartite)

richness<-matrix(0,40,4)

plants<- c("Interaccions","Bitxos","Plantes","Dia")

parceles<-c("1x","2x","3x","4x","5x","6x","7x","8x","9x","10x","11x","12x","13x","14x","15x","16x","17x","18x","19x","20x","21x","22x","23x","24x","25x","26x","27x","28x","29x","30x","31x","32x","33x","34x","35x","36x","37x","38x","39x","40x")

dia<-c(4,11,1,2,4,1,5,11,11,2,14,1,5,11,13,10,14,13,16,16,16,13,10,13,9,4,10,6,14,12,6,5,12,7,8,2,8,7,2,9)

richness[,4]<-dia

colnames(richness)<-plants
rownames(richness)<-parceles

plot1<-read.csv("plot1.csv",header=T)
plot1_interactions<-data.frame(plot1$Bitxo,plot1$Planta)
plot1_bitxos<-data.frame(plot1$Bitxo)
plot1_plantes<-data.frame(plot1$Planta)
plot1_unique_interaccions<-unique(plot1_interactions)
plot1_unique_bitxos<-unique(plot1_bitxos)
plot1_unique_plantes<-unique(plot1_plantes)
richness[1,1]<-nrow(plot1_unique_interaccions)
richness[1,2]<-nrow(plot1_unique_bitxos)
richness[1,3]<-nrow(plot1_unique_plantes)

plot2<-read.csv("plot2.csv",header=T)
plot2_interactions<-data.frame(plot2$Bitxo,plot2$Planta)
plot2_bitxos<-data.frame(plot2$Bitxo)
plot2_plantes<-data.frame(plot2$Planta)
plot2_unique_interaccions<-unique(plot2_interactions)
plot2_unique_bitxos<-unique(plot2_bitxos)
plot2_unique_plantes<-unique(plot2_plantes)
richness[2,1]<-nrow(plot2_unique_interaccions)
richness[2,2]<-nrow(plot2_unique_bitxos)
richness[2,3]<-nrow(plot2_unique_plantes)

plot3<-read.csv("plot3.csv",header=T)
plot3_interactions<-data.frame(plot3$Bitxo,plot3$Planta)
plot3_bitxos<-data.frame(plot3$Bitxo)
plot3_plantes<-data.frame(plot3$Planta)
plot3_unique_interaccions<-unique(plot3_interactions)
plot3_unique_bitxos<-unique(plot3_bitxos)
plot3_unique_plantes<-unique(plot3_plantes)
richness[3,1]<-nrow(plot3_unique_interaccions)
richness[3,2]<-nrow(plot3_unique_bitxos)
richness[3,3]<-nrow(plot3_unique_plantes)

plot4<-read.csv("plot4.csv",header=T)
plot4_interactions<-data.frame(plot4$Bitxo,plot4$Planta)
plot4_bitxos<-data.frame(plot4$Bitxo)
plot4_plantes<-data.frame(plot4$Planta)
plot4_unique_interaccions<-unique(plot4_interactions)
plot4_unique_bitxos<-unique(plot4_bitxos)
plot4_unique_plantes<-unique(plot4_plantes)
richness[4,1]<-nrow(plot4_unique_interaccions)
richness[4,2]<-nrow(plot4_unique_bitxos)
richness[4,3]<-nrow(plot4_unique_plantes)

plot5<-read.csv("plot5.csv",header=T)
plot5_interactions<-data.frame(plot5$Bitxo,plot5$Planta)
plot5_bitxos<-data.frame(plot5$Bitxo)
plot5_plantes<-data.frame(plot5$Planta)
plot5_unique_interaccions<-unique(plot5_interactions)
plot5_unique_bitxos<-unique(plot5_bitxos)
plot5_unique_plantes<-unique(plot5_plantes)
richness[5,1]<-nrow(plot5_unique_interaccions)
richness[5,2]<-nrow(plot5_unique_bitxos)
richness[5,3]<-nrow(plot5_unique_plantes)

plot6<-read.csv("plot6.csv",header=T)
plot6_interactions<-data.frame(plot6$Bitxo,plot6$Planta)
plot6_bitxos<-data.frame(plot6$Bitxo)
plot6_plantes<-data.frame(plot6$Planta)
plot6_unique_interaccions<-unique(plot6_interactions)
plot6_unique_bitxos<-unique(plot6_bitxos)
plot6_unique_plantes<-unique(plot6_plantes)
richness[6,1]<-nrow(plot6_unique_interaccions)
richness[6,2]<-nrow(plot6_unique_bitxos)
richness[6,3]<-nrow(plot6_unique_plantes)

plot7<-read.csv("plot7.csv",header=T)
plot7_interactions<-data.frame(plot7$Bitxo,plot7$Planta)
plot7_bitxos<-data.frame(plot7$Bitxo)
plot7_plantes<-data.frame(plot7$Planta)
plot7_unique_interaccions<-unique(plot7_interactions)
plot7_unique_bitxos<-unique(plot7_bitxos)
plot7_unique_plantes<-unique(plot7_plantes)
richness[7,1]<-nrow(plot7_unique_interaccions)
richness[7,2]<-nrow(plot7_unique_bitxos)
richness[7,3]<-nrow(plot7_unique_plantes)

plot8<-read.csv("plot8.csv",header=T)
plot8_interactions<-data.frame(plot8$Bitxo,plot8$Planta)
plot8_bitxos<-data.frame(plot8$Bitxo)
plot8_plantes<-data.frame(plot8$Planta)
plot8_unique_interaccions<-unique(plot8_interactions)
plot8_unique_bitxos<-unique(plot8_bitxos)
plot8_unique_plantes<-unique(plot8_plantes)
richness[8,1]<-nrow(plot8_unique_interaccions)
richness[8,2]<-nrow(plot8_unique_bitxos)
richness[8,3]<-nrow(plot8_unique_plantes)

plot9<-read.csv("plot9.csv",header=T)
plot9_interactions<-data.frame(plot9$Bitxo,plot9$Planta)
plot9_bitxos<-data.frame(plot9$Bitxo)
plot9_plantes<-data.frame(plot9$Planta)
plot9_unique_interaccions<-unique(plot9_interactions)
plot9_unique_bitxos<-unique(plot9_bitxos)
plot9_unique_plantes<-unique(plot9_plantes)
richness[9,1]<-nrow(plot9_unique_interaccions)
richness[9,2]<-nrow(plot9_unique_bitxos)
richness[9,3]<-nrow(plot9_unique_plantes)

plot10<-read.csv("plot10.csv",header=T)
plot10_interactions<-data.frame(plot10$Bitxo,plot10$Planta)
plot10_bitxos<-data.frame(plot10$Bitxo)
plot10_plantes<-data.frame(plot10$Planta)
plot10_unique_interaccions<-unique(plot10_interactions)
plot10_unique_bitxos<-unique(plot10_bitxos)
plot10_unique_plantes<-unique(plot10_plantes)
richness[10,1]<-nrow(plot10_unique_interaccions)
richness[10,2]<-nrow(plot10_unique_bitxos)
richness[10,3]<-nrow(plot10_unique_plantes)

plot11<-read.csv("plot11.csv",header=T)
plot11_interactions<-data.frame(plot11$Bitxo,plot11$Planta)
plot11_bitxos<-data.frame(plot11$Bitxo)
plot11_plantes<-data.frame(plot11$Planta)
plot11_unique_interaccions<-unique(plot11_interactions)
plot11_unique_bitxos<-unique(plot11_bitxos)
plot11_unique_plantes<-unique(plot11_plantes)
richness[11,1]<-nrow(plot11_unique_interaccions)
richness[11,2]<-nrow(plot11_unique_bitxos)
richness[11,3]<-nrow(plot11_unique_plantes)

plot12<-read.csv("plot12.csv",header=T)
plot12_interactions<-data.frame(plot12$Bitxo,plot12$Planta)
plot12_bitxos<-data.frame(plot12$Bitxo)
plot12_plantes<-data.frame(plot12$Planta)
plot12_unique_interaccions<-unique(plot12_interactions)
plot12_unique_bitxos<-unique(plot12_bitxos)
plot12_unique_plantes<-unique(plot12_plantes)
richness[12,1]<-nrow(plot12_unique_interaccions)
richness[12,2]<-nrow(plot12_unique_bitxos)
richness[12,3]<-nrow(plot12_unique_plantes)


plot13<-read.csv("plot13.csv",header=T)
plot13_interactions<-data.frame(plot13$Bitxo,plot13$Planta)
plot13_bitxos<-data.frame(plot13$Bitxo)
plot13_plantes<-data.frame(plot13$Planta)
plot13_unique_interaccions<-unique(plot13_interactions)
plot13_unique_bitxos<-unique(plot13_bitxos)
plot13_unique_plantes<-unique(plot13_plantes)
richness[13,1]<-nrow(plot13_unique_interaccions)
richness[13,2]<-nrow(plot13_unique_bitxos)
richness[13,3]<-nrow(plot13_unique_plantes)


plot14<-read.csv("plot14.csv",header=T)
plot14_interactions<-data.frame(plot14$Bitxo,plot14$Planta)
plot14_bitxos<-data.frame(plot14$Bitxo)
plot14_plantes<-data.frame(plot14$Planta)
plot14_unique_interaccions<-unique(plot14_interactions)
plot14_unique_bitxos<-unique(plot14_bitxos)
plot14_unique_plantes<-unique(plot14_plantes)
richness[14,1]<-nrow(plot14_unique_interaccions)
richness[14,2]<-nrow(plot14_unique_bitxos)
richness[14,3]<-nrow(plot14_unique_plantes)


plot15<-read.csv("plot15.csv",header=T)
plot15_interactions<-data.frame(plot15$Bitxo,plot15$Planta)
plot15_bitxos<-data.frame(plot15$Bitxo)
plot15_plantes<-data.frame(plot15$Planta)
plot15_unique_interaccions<-unique(plot15_interactions)
plot15_unique_bitxos<-unique(plot15_bitxos)
plot15_unique_plantes<-unique(plot15_plantes)
richness[15,1]<-nrow(plot15_unique_interaccions)
richness[15,2]<-nrow(plot15_unique_bitxos)
richness[15,3]<-nrow(plot15_unique_plantes)


plot16<-read.csv("plot16.csv",header=T)
plot16_interactions<-data.frame(plot16$Bitxo,plot16$Planta)
plot16_bitxos<-data.frame(plot16$Bitxo)
plot16_plantes<-data.frame(plot16$Planta)
plot16_unique_interaccions<-unique(plot16_interactions)
plot16_unique_bitxos<-unique(plot16_bitxos)
plot16_unique_plantes<-unique(plot16_plantes)
richness[16,1]<-nrow(plot16_unique_interaccions)
richness[16,2]<-nrow(plot16_unique_bitxos)
richness[16,3]<-nrow(plot16_unique_plantes)


plot17<-read.csv("plot17.csv",header=T)
plot17_interactions<-data.frame(plot17$Bitxo,plot17$Planta)
plot17_bitxos<-data.frame(plot17$Bitxo)
plot17_plantes<-data.frame(plot17$Planta)
plot17_unique_interaccions<-unique(plot17_interactions)
plot17_unique_bitxos<-unique(plot17_bitxos)
plot17_unique_plantes<-unique(plot17_plantes)
richness[17,1]<-nrow(plot17_unique_interaccions)
richness[17,2]<-nrow(plot17_unique_bitxos)
richness[17,3]<-nrow(plot17_unique_plantes)


plot18<-read.csv("plot18.csv",header=T)
plot18_interactions<-data.frame(plot18$Bitxo,plot18$Planta)
plot18_bitxos<-data.frame(plot18$Bitxo)
plot18_plantes<-data.frame(plot18$Planta)
plot18_unique_interaccions<-unique(plot18_interactions)
plot18_unique_bitxos<-unique(plot18_bitxos)
plot18_unique_plantes<-unique(plot18_plantes)
richness[18,1]<-nrow(plot18_unique_interaccions)
richness[18,2]<-nrow(plot18_unique_bitxos)
richness[18,3]<-nrow(plot18_unique_plantes)


plot19<-read.csv("plot19.csv",header=T)
plot19_interactions<-data.frame(plot19$Bitxo,plot19$Planta)
plot19_bitxos<-data.frame(plot19$Bitxo)
plot19_plantes<-data.frame(plot19$Planta)
plot19_unique_interaccions<-unique(plot19_interactions)
plot19_unique_bitxos<-unique(plot19_bitxos)
plot19_unique_plantes<-unique(plot19_plantes)
richness[19,1]<-nrow(plot19_unique_interaccions)
richness[19,2]<-nrow(plot19_unique_bitxos)
richness[19,3]<-nrow(plot19_unique_plantes)

plot20<-read.csv("plot20.csv",header=T)
plot20_interactions<-data.frame(plot20$Bitxo,plot20$Planta)
plot20_bitxos<-data.frame(plot20$Bitxo)
plot20_plantes<-data.frame(plot20$Planta)
plot20_unique_interaccions<-unique(plot20_interactions)
plot20_unique_bitxos<-unique(plot20_bitxos)
plot20_unique_plantes<-unique(plot20_plantes)
richness[20,1]<-nrow(plot20_unique_interaccions)
richness[20,2]<-nrow(plot20_unique_bitxos)
richness[20,3]<-nrow(plot20_unique_plantes)


plot21<-read.csv("plot21.csv",header=T)
plot21_interactions<-data.frame(plot21$Bitxo,plot21$Planta)
plot21_bitxos<-data.frame(plot21$Bitxo)
plot21_plantes<-data.frame(plot21$Planta)
plot21_unique_interaccions<-unique(plot21_interactions)
plot21_unique_bitxos<-unique(plot21_bitxos)
plot21_unique_plantes<-unique(plot21_plantes)
richness[21,1]<-nrow(plot21_unique_interaccions)
richness[21,2]<-nrow(plot21_unique_bitxos)
richness[21,3]<-nrow(plot21_unique_plantes)

plot22<-read.csv("plot22.csv",header=T)
plot22_interactions<-data.frame(plot22$Bitxo,plot22$Planta)
plot22_bitxos<-data.frame(plot22$Bitxo)
plot22_plantes<-data.frame(plot22$Planta)
plot22_unique_interaccions<-unique(plot22_interactions)
plot22_unique_bitxos<-unique(plot22_bitxos)
plot22_unique_plantes<-unique(plot22_plantes)
richness[22,1]<-nrow(plot22_unique_interaccions)
richness[22,2]<-nrow(plot22_unique_bitxos)
richness[22,3]<-nrow(plot22_unique_plantes)

plot23<-read.csv("plot23.csv",header=T)
plot23_interactions<-data.frame(plot23$Bitxo,plot23$Planta)
plot23_bitxos<-data.frame(plot23$Bitxo)
plot23_plantes<-data.frame(plot23$Planta)
plot23_unique_interaccions<-unique(plot23_interactions)
plot23_unique_bitxos<-unique(plot23_bitxos)
plot23_unique_plantes<-unique(plot23_plantes)
richness[23,1]<-nrow(plot23_unique_interaccions)
richness[23,2]<-nrow(plot23_unique_bitxos)
richness[23,3]<-nrow(plot23_unique_plantes)

plot24<-read.csv("plot24.csv",header=T)
plot24_interactions<-data.frame(plot24$Bitxo,plot24$Planta)
plot24_bitxos<-data.frame(plot24$Bitxo)
plot24_plantes<-data.frame(plot24$Planta)
plot24_unique_interaccions<-unique(plot24_interactions)
plot24_unique_bitxos<-unique(plot24_bitxos)
plot24_unique_plantes<-unique(plot24_plantes)
richness[24,1]<-nrow(plot24_unique_interaccions)
richness[24,2]<-nrow(plot24_unique_bitxos)
richness[24,3]<-nrow(plot24_unique_plantes)

plot25<-read.csv("plot25.csv",header=T)
plot25_interactions<-data.frame(plot25$Bitxo,plot25$Planta)
plot25_bitxos<-data.frame(plot25$Bitxo)
plot25_plantes<-data.frame(plot25$Planta)
plot25_unique_interaccions<-unique(plot25_interactions)
plot25_unique_bitxos<-unique(plot25_bitxos)
plot25_unique_plantes<-unique(plot25_plantes)
richness[25,1]<-nrow(plot25_unique_interaccions)
richness[25,2]<-nrow(plot25_unique_bitxos)
richness[25,3]<-nrow(plot25_unique_plantes)

plot26<-read.csv("plot26.csv",header=T)
plot26_interactions<-data.frame(plot26$Bitxo,plot26$Planta)
plot26_bitxos<-data.frame(plot26$Bitxo)
plot26_plantes<-data.frame(plot26$Planta)
plot26_unique_interaccions<-unique(plot26_interactions)
plot26_unique_bitxos<-unique(plot26_bitxos)
plot26_unique_plantes<-unique(plot26_plantes)
richness[26,1]<-nrow(plot26_unique_interaccions)
richness[26,2]<-nrow(plot26_unique_bitxos)
richness[26,3]<-nrow(plot26_unique_plantes)

plot27<-read.csv("plot27.csv",header=T)
plot27_interactions<-data.frame(plot27$Bitxo,plot27$Planta)
plot27_bitxos<-data.frame(plot27$Bitxo)
plot27_plantes<-data.frame(plot27$Planta)
plot27_unique_interaccions<-unique(plot27_interactions)
plot27_unique_bitxos<-unique(plot27_bitxos)
plot27_unique_plantes<-unique(plot27_plantes)
richness[27,1]<-nrow(plot27_unique_interaccions)
richness[27,2]<-nrow(plot27_unique_bitxos)
richness[27,3]<-nrow(plot27_unique_plantes)

plot28<-read.csv("plot28.csv",header=T)
plot28_interactions<-data.frame(plot28$Bitxo,plot28$Planta)
plot28_bitxos<-data.frame(plot28$Bitxo)
plot28_plantes<-data.frame(plot28$Planta)
plot28_unique_interaccions<-unique(plot28_interactions)
plot28_unique_bitxos<-unique(plot28_bitxos)
plot28_unique_plantes<-unique(plot28_plantes)
richness[28,1]<-nrow(plot28_unique_interaccions)
richness[28,2]<-nrow(plot28_unique_bitxos)
richness[28,3]<-nrow(plot28_unique_plantes)

plot29<-read.csv("plot29.csv",header=T)
plot29_interactions<-data.frame(plot29$Bitxo,plot29$Planta)
plot29_bitxos<-data.frame(plot29$Bitxo)
plot29_plantes<-data.frame(plot29$Planta)
plot29_unique_interaccions<-unique(plot29_interactions)
plot29_unique_bitxos<-unique(plot29_bitxos)
plot29_unique_plantes<-unique(plot29_plantes)
richness[29,1]<-nrow(plot29_unique_interaccions)
richness[29,2]<-nrow(plot29_unique_bitxos)
richness[29,3]<-nrow(plot29_unique_plantes)

plot30<-read.csv("plot30.csv",header=T)
plot30_interactions<-data.frame(plot30$Bitxo,plot30$Planta)
plot30_bitxos<-data.frame(plot30$Bitxo)
plot30_plantes<-data.frame(plot30$Planta)
plot30_unique_interaccions<-unique(plot30_interactions)
plot30_unique_bitxos<-unique(plot30_bitxos)
plot30_unique_plantes<-unique(plot30_plantes)
richness[30,1]<-nrow(plot30_unique_interaccions)
richness[30,2]<-nrow(plot30_unique_bitxos)
richness[30,3]<-nrow(plot30_unique_plantes)

plot31<-read.csv("plot31.csv",header=T)
plot31_interactions<-data.frame(plot31$Bitxo,plot31$Planta)
plot31_bitxos<-data.frame(plot31$Bitxo)
plot31_plantes<-data.frame(plot31$Planta)
plot31_unique_interaccions<-unique(plot31_interactions)
plot31_unique_bitxos<-unique(plot31_bitxos)
plot31_unique_plantes<-unique(plot31_plantes)
richness[31,1]<-nrow(plot31_unique_interaccions)
richness[31,2]<-nrow(plot31_unique_bitxos)
richness[31,3]<-nrow(plot31_unique_plantes)

plot32<-read.csv("plot32.csv",header=T)
plot32_interactions<-data.frame(plot32$Bitxo,plot32$Planta)
plot32_bitxos<-data.frame(plot32$Bitxo)
plot32_plantes<-data.frame(plot32$Planta)
plot32_unique_interaccions<-unique(plot32_interactions)
plot32_unique_bitxos<-unique(plot32_bitxos)
plot32_unique_plantes<-unique(plot32_plantes)
richness[32,1]<-nrow(plot32_unique_interaccions)
richness[32,2]<-nrow(plot32_unique_bitxos)
richness[32,3]<-nrow(plot32_unique_plantes)

plot33<-read.csv("plot33.csv",header=T)
plot33_interactions<-data.frame(plot33$Bitxo,plot33$Planta)
plot33_bitxos<-data.frame(plot33$Bitxo)
plot33_plantes<-data.frame(plot33$Planta)
plot33_unique_interaccions<-unique(plot33_interactions)
plot33_unique_bitxos<-unique(plot33_bitxos)
plot33_unique_plantes<-unique(plot33_plantes)
richness[33,1]<-nrow(plot33_unique_interaccions)
richness[33,2]<-nrow(plot33_unique_bitxos)
richness[33,3]<-nrow(plot33_unique_plantes)

plot34<-read.csv("plot34.csv",header=T)
plot34_interactions<-data.frame(plot34$Bitxo,plot34$Planta)
plot34_bitxos<-data.frame(plot34$Bitxo)
plot34_plantes<-data.frame(plot34$Planta)
plot34_unique_interaccions<-unique(plot34_interactions)
plot34_unique_bitxos<-unique(plot34_bitxos)
plot34_unique_plantes<-unique(plot34_plantes)
richness[34,1]<-nrow(plot34_unique_interaccions)
richness[34,2]<-nrow(plot34_unique_bitxos)
richness[34,3]<-nrow(plot34_unique_plantes)

plot35<-read.csv("plot35.csv",header=T)
plot35_interactions<-data.frame(plot35$Bitxo,plot35$Planta)
plot35_bitxos<-data.frame(plot35$Bitxo)
plot35_plantes<-data.frame(plot35$Planta)
plot35_unique_interaccions<-unique(plot35_interactions)
plot35_unique_bitxos<-unique(plot35_bitxos)
plot35_unique_plantes<-unique(plot35_plantes)
richness[35,1]<-nrow(plot35_unique_interaccions)
richness[35,2]<-nrow(plot35_unique_bitxos)
richness[35,3]<-nrow(plot35_unique_plantes)

plot36<-read.csv("plot36.csv",header=T)
plot36_interactions<-data.frame(plot36$Bitxo,plot36$Planta)
plot36_bitxos<-data.frame(plot36$Bitxo)
plot36_plantes<-data.frame(plot36$Planta)
plot36_unique_interaccions<-unique(plot36_interactions)
plot36_unique_bitxos<-unique(plot36_bitxos)
plot36_unique_plantes<-unique(plot36_plantes)
richness[36,1]<-nrow(plot36_unique_interaccions)
richness[36,2]<-nrow(plot36_unique_bitxos)
richness[36,3]<-nrow(plot36_unique_plantes)

plot37<-read.csv("plot37.csv",header=T)
plot37_interactions<-data.frame(plot37$Bitxo,plot37$Planta)
plot37_bitxos<-data.frame(plot37$Bitxo)
plot37_plantes<-data.frame(plot37$Planta)
plot37_unique_interaccions<-unique(plot37_interactions)
plot37_unique_bitxos<-unique(plot37_bitxos)
plot37_unique_plantes<-unique(plot37_plantes)
richness[37,1]<-nrow(plot37_unique_interaccions)
richness[37,2]<-nrow(plot37_unique_bitxos)
richness[37,3]<-nrow(plot37_unique_plantes)

plot38<-read.csv("plot38.csv",header=T)
plot38_interactions<-data.frame(plot38$Bitxo,plot38$Planta)
plot38_bitxos<-data.frame(plot38$Bitxo)
plot38_plantes<-data.frame(plot38$Planta)
plot38_unique_interaccions<-unique(plot38_interactions)
plot38_unique_bitxos<-unique(plot38_bitxos)
plot38_unique_plantes<-unique(plot38_plantes)
richness[38,1]<-nrow(plot38_unique_interaccions)
richness[38,2]<-nrow(plot38_unique_bitxos)
richness[38,3]<-nrow(plot38_unique_plantes)

plot39<-read.csv("plot39.csv",header=T)
plot39_interactions<-data.frame(plot39$Bitxo,plot39$Planta)
plot39_bitxos<-data.frame(plot39$Bitxo)
plot39_plantes<-data.frame(plot39$Planta)
plot39_unique_interaccions<-unique(plot39_interactions)
plot39_unique_bitxos<-unique(plot39_bitxos)
plot39_unique_plantes<-unique(plot39_plantes)
richness[39,1]<-nrow(plot39_unique_interaccions)
richness[39,2]<-nrow(plot39_unique_bitxos)
richness[39,3]<-nrow(plot39_unique_plantes)

plot40<-read.csv("plot40.csv",header=T)
plot40_interactions<-data.frame(plot40$Bitxo,plot40$Planta)
plot40_bitxos<-data.frame(plot40$Bitxo)
plot40_plantes<-data.frame(plot40$Planta)
plot40_unique_interaccions<-unique(plot40_interactions)
plot40_unique_bitxos<-unique(plot40_bitxos)
plot40_unique_plantes<-unique(plot40_plantes)
richness[40,1]<-nrow(plot40_unique_interaccions)
richness[40,2]<-nrow(plot40_unique_bitxos)
richness[40,3]<-nrow(plot40_unique_plantes)

plot11<-read.csv("plot11.csv",header=T)
plot11_interactions<-data.frame(plot11$Bitxo,plot11$Planta)
plot11_bitxos<-data.frame(plot11$Bitxo)
plot11_plantes<-data.frame(plot11$Planta)
plot11_unique_interaccions<-unique(plot11_interactions)
plot11_unique_bitxos<-unique(plot11_bitxos)
plot11_unique_plantes<-unique(plot11_plantes)
richness[11,1]<-nrow(plot11_unique_interaccions)
richness[11,2]<-nrow(plot11_unique_bitxos)
richness[11,3]<-nrow(plot11_unique_plantes)

reg<-lm(richness[,4] ~ richness[,1])
reg<-lm(richness[,4] ~ richness[,2])
reg<-lm(richness[,4] ~ richness[,3])

summary(reg)


write.csv(richness,"D:\\Usuarios\\s.reverte\\Desktop\\TESI\\DADES\\Nombre espècies plantes i insectes.csv")
